<?php

namespace Proxies\__CG__\Apartamentos\ApartamentosBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Apartment extends \Apartamentos\ApartamentosBundle\Entity\Apartment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'number', 'phone', 'area', 'numberresidents', 'floornumber', 'rooms', 'hasmade', 'hasbabysitting', 'haspet', 'hasmaderoom', 'haskids', 'numberofkids', 'petkind', 'petnumber', 'towerid', 'companyid', 'createdate', 'createuser', 'modifydate', 'modifyuser');
        }

        return array('__isInitialized__', 'id', 'number', 'phone', 'area', 'numberresidents', 'floornumber', 'rooms', 'hasmade', 'hasbabysitting', 'haspet', 'hasmaderoom', 'haskids', 'numberofkids', 'petkind', 'petnumber', 'towerid', 'companyid', 'createdate', 'createuser', 'modifydate', 'modifyuser');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Apartment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', array($number));

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', array());

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setArea($area)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea', array($area));

        return parent::setArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function getArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', array());

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberresidents($numberresidents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberresidents', array($numberresidents));

        return parent::setNumberresidents($numberresidents);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberresidents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberresidents', array());

        return parent::getNumberresidents();
    }

    /**
     * {@inheritDoc}
     */
    public function setFloornumber($floornumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFloornumber', array($floornumber));

        return parent::setFloornumber($floornumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getFloornumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFloornumber', array());

        return parent::getFloornumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setRooms($rooms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRooms', array($rooms));

        return parent::setRooms($rooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getRooms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRooms', array());

        return parent::getRooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasmade($hasmade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasmade', array($hasmade));

        return parent::setHasmade($hasmade);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasmade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasmade', array());

        return parent::getHasmade();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasbabysitting($hasbabysitting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasbabysitting', array($hasbabysitting));

        return parent::setHasbabysitting($hasbabysitting);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasbabysitting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasbabysitting', array());

        return parent::getHasbabysitting();
    }

    /**
     * {@inheritDoc}
     */
    public function setHaspet($haspet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHaspet', array($haspet));

        return parent::setHaspet($haspet);
    }

    /**
     * {@inheritDoc}
     */
    public function getHaspet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHaspet', array());

        return parent::getHaspet();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasmaderoom($hasmaderoom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasmaderoom', array($hasmaderoom));

        return parent::setHasmaderoom($hasmaderoom);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasmaderoom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasmaderoom', array());

        return parent::getHasmaderoom();
    }

    /**
     * {@inheritDoc}
     */
    public function setHaskids($haskids)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHaskids', array($haskids));

        return parent::setHaskids($haskids);
    }

    /**
     * {@inheritDoc}
     */
    public function getHaskids()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHaskids', array());

        return parent::getHaskids();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberofkids($numberofkids)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberofkids', array($numberofkids));

        return parent::setNumberofkids($numberofkids);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberofkids()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberofkids', array());

        return parent::getNumberofkids();
    }

    /**
     * {@inheritDoc}
     */
    public function setPetkind($petkind)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPetkind', array($petkind));

        return parent::setPetkind($petkind);
    }

    /**
     * {@inheritDoc}
     */
    public function getPetkind()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPetkind', array());

        return parent::getPetkind();
    }

    /**
     * {@inheritDoc}
     */
    public function setPetnumber($petnumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPetnumber', array($petnumber));

        return parent::setPetnumber($petnumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPetnumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPetnumber', array());

        return parent::getPetnumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setTowerid(\Apartamentos\ApartamentosBundle\Entity\Tower $towerid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTowerid', array($towerid));

        return parent::setTowerid($towerid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTowerid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTowerid', array());

        return parent::getTowerid();
    }

    /**
     * {@inheritDoc}
     */
    public function getApartmentTower()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApartmentTower', array());

        return parent::getApartmentTower();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyid($companyid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyid', array($companyid));

        return parent::setCompanyid($companyid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyid', array());

        return parent::getCompanyid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedate($createdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedate', array($createdate));

        return parent::setCreatedate($createdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedate', array());

        return parent::getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifydate($modifydate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifydate', array($modifydate));

        return parent::setModifydate($modifydate);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifydate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifydate', array());

        return parent::getModifydate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateuser($createuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateuser', array($createuser));

        return parent::setCreateuser($createuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateuser', array());

        return parent::getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifyuser($modifyuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifyuser', array($modifyuser));

        return parent::setModifyuser($modifyuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifyuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifyuser', array());

        return parent::getModifyuser();
    }

}
