<?php

namespace Proxies\__CG__\Apartamentos\ApartamentosBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Resident extends \Apartamentos\ApartamentosBundle\Entity\Resident implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'idnumber', 'name', 'idnumbertype', 'holder', 'email', 'phone', 'apartmentid', 'residenttypeid', 'towerid', 'companyid', 'createdate', 'createuser', 'modifydate', 'modifyuser');
        }

        return array('__isInitialized__', 'id', 'idnumber', 'name', 'idnumbertype', 'holder', 'email', 'phone', 'apartmentid', 'residenttypeid', 'towerid', 'companyid', 'createdate', 'createuser', 'modifydate', 'modifyuser');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Resident $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdnumber($idnumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdnumber', array($idnumber));

        return parent::setIdnumber($idnumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdnumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdnumber', array());

        return parent::getIdnumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdnumbertype($idnumbertype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdnumbertype', array($idnumbertype));

        return parent::setIdnumbertype($idnumbertype);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdnumbertype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdnumbertype', array());

        return parent::getIdnumbertype();
    }

    /**
     * {@inheritDoc}
     */
    public function setHolder($holder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHolder', array($holder));

        return parent::setHolder($holder);
    }

    /**
     * {@inheritDoc}
     */
    public function getHolder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHolder', array());

        return parent::getHolder();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setApartmentid(\Apartamentos\ApartamentosBundle\Entity\Apartment $apartmentid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApartmentid', array($apartmentid));

        return parent::setApartmentid($apartmentid);
    }

    /**
     * {@inheritDoc}
     */
    public function getApartmentid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApartmentid', array());

        return parent::getApartmentid();
    }

    /**
     * {@inheritDoc}
     */
    public function setResidenttypeid(\Apartamentos\ApartamentosBundle\Entity\Residenttype $residenttypeid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResidenttypeid', array($residenttypeid));

        return parent::setResidenttypeid($residenttypeid);
    }

    /**
     * {@inheritDoc}
     */
    public function getResidenttypeid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResidenttypeid', array());

        return parent::getResidenttypeid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTowerid(\Apartamentos\ApartamentosBundle\Entity\Tower $towerid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTowerid', array($towerid));

        return parent::setTowerid($towerid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTowerid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTowerid', array());

        return parent::getTowerid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyid($companyid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyid', array($companyid));

        return parent::setCompanyid($companyid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyid', array());

        return parent::getCompanyid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedate($createdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedate', array($createdate));

        return parent::setCreatedate($createdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedate', array());

        return parent::getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifydate($modifydate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifydate', array($modifydate));

        return parent::setModifydate($modifydate);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifydate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifydate', array());

        return parent::getModifydate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateuser($createuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateuser', array($createuser));

        return parent::setCreateuser($createuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateuser', array());

        return parent::getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifyuser($modifyuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifyuser', array($modifyuser));

        return parent::setModifyuser($modifyuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifyuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifyuser', array());

        return parent::getModifyuser();
    }

}
